#!/usr/bin/env bash
docker run --rm -it \
  -v ~/.ssh/id_dsa:/root/.ssh/id_dsa \
  -v ~/.ssh/id_dsa.pub:/root/.ssh/id_dsa.pub \
  -v ~/Dev/Docker/ansible:/etc/ansible \
  -v ~/Dev/Docker/ansible/playbooks:/ansible/playbooks \
  -v /var/log/ansible/ansible.log \
  walokra/ansible-playbook "$@"